#!/bin/bash

#dir=$(dirname $(which qsub_jobs_threads))  # dirname of qsub_jobs_threads.py
dir='/mnt/hwt2_data1/xingqian/bin/qsub_jobs_threads3'

if [[ $# < 3 ]]; then
	python3 $dir/qsub_jobs_threads_xqmk.py $@
else
	echo 'Please check details in file "log_SGE.out" and directory "log_SGE"'
	nohup python3 -u $dir/qsub_jobs_threads_xqmk.py $@ >> log_SGE.out 2>&1 &
fi
