#!/bin/bash

#dir=$(dirname $(which qsub_jobs_threads))  # dirname of qsub_jobs_threads.py
dir='/lustre/zhouze/Software/qsub_jobs_threads'

if [[ $# < 3 ]]; then
	python3 $dir/qsub_jobs_threads.py $@
else
	echo 'Please check details in file "log_SGE.out" and directory "log_SGE"'
	nohup python3 -u $dir/qsub_jobs_threads.py $@ >> log_SGE.out 2>&1 &
fi
