#!/bin/bash

#dir=$(dirname $(which slurm_jobs_threads))  # dirname of qsub_jobs_threads.py
dir='/mnt/dt2_dc2stor_data202/lixq/test_slurm/qsub_jobs_threads4'

if [[ $# < 3 ]]; then
	python3 $dir/slurm_jobs_threads.py $@
else
	echo 'Please check details in file "log_SGE.out" and directory "log_SLURM"'
	nohup python3 -u $dir/slurm_jobs_threads.py $@ >> log_Slurm.out 2>&1 &
fi
